//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ;Initial Catalog=PARQUEO2;Persist Security Info=True;U" +
            "ser ID=sa;Password=informatica@2017")]
        public string PARQUEO2ConnectionString {
            get {
                return ((string)(this["PARQUEO2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ\\;Initial Catalog=PARQUEO2;Persist Security Info=True;" +
            "User ID=SA;Password=informatica@2017")]
        public string PARQUEO2ConnectionString1 {
            get {
                return ((string)(this["PARQUEO2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ;Initial Catalog=PARQUEO2;User ID=sa;Password=informat" +
            "ica@2017")]
        public string PARQUEO2ConnectionString2 {
            get {
                return ((string)(this["PARQUEO2ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ;Initial Catalog=PARQUEO00;Integrated Security=True")]
        public string PARQUEO00ConnectionString {
            get {
                return ((string)(this["PARQUEO00ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ\\;Initial Catalog=PARQUEO00;Integrated Security=True")]
        public string PARQUEO00ConnectionString1 {
            get {
                return ((string)(this["PARQUEO00ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ\\;Initial Catalog=PARQUEO01;Integrated Security=True")]
        public string PARQUEO01ConnectionString {
            get {
                return ((string)(this["PARQUEO01ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ;Initial Catalog=PARQUEO01;Integrated Security=True")]
        public string PARQUEO01ConnectionString1 {
            get {
                return ((string)(this["PARQUEO01ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ;Initial Catalog=PARQUEO02122021;Integrated Security=T" +
            "rue")]
        public string PARQUEO02122021ConnectionString {
            get {
                return ((string)(this["PARQUEO02122021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ;Initial Catalog=PARQUEO2122021;Integrated Security=Tr" +
            "ue")]
        public string PARQUEO2122021ConnectionString {
            get {
                return ((string)(this["PARQUEO2122021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ;Initial Catalog=parqueo21220211;Integrated Security=T" +
            "rue")]
        public string parqueo21220211ConnectionString {
            get {
                return ((string)(this["parqueo21220211ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ;Initial Catalog=parqueo02122021;Integrated Security=T" +
            "rue")]
        public string parqueo02122021ConnectionString1 {
            get {
                return ((string)(this["parqueo02122021ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-THCA3D774KJ;Initial Catalog=PARQUEO01122021;Integrated Security=T" +
            "rue")]
        public string PARQUEO01122021ConnectionString {
            get {
                return ((string)(this["PARQUEO01122021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1QD2KM3;Initial Catalog=PARQUEO02122021];Integrated Security=" +
            "True")]
        public string PARQUEO02122021_ConnectionString {
            get {
                return ((string)(this["PARQUEO02122021_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO02_05122021;Integrated Security=" +
            "True")]
        public string PARQUEO02_05122021ConnectionString {
            get {
                return ((string)(this["PARQUEO02_05122021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO02_05122021;Integrated Security=" +
            "True")]
        public string PARQUEO02_05122021ConnectionString1 {
            get {
                return ((string)(this["PARQUEO02_05122021ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO02_05122021;User ID=sa;Password=" +
            "informatica@2017")]
        public string PARQUEO02_05122021ConnectionString2 {
            get {
                return ((string)(this["PARQUEO02_05122021ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_09122021;Integrated Security=" +
            "True")]
        public string PARQUEO03_09122021ConnectionString {
            get {
                return ((string)(this["PARQUEO03_09122021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_09122021;Persist Security Inf" +
            "o=True;User ID=sa;Password=informatica@2017")]
        public string PARQUEO03_09122021ConnectionString1 {
            get {
                return ((string)(this["PARQUEO03_09122021ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021;User ID=sa;Password=" +
            "informatica@2017")]
        public string PARQUEO03_30122021ConnectionString {
            get {
                return ((string)(this["PARQUEO03_30122021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021_pruebas;User ID=sa;P" +
            "assword=informatica@2017")]
        public string PARQUEO03_30122021_pruebasConnectionString {
            get {
                return ((string)(this["PARQUEO03_30122021_pruebasConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021_pruebas;Integrated S" +
            "ecurity=True")]
        public string PARQUEO03_30122021_pruebasConnectionString1 {
            get {
                return ((string)(this["PARQUEO03_30122021_pruebasConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1QD2KM3;Initial Catalog=PARQUEO03_30122021;User ID=sa;Passwor" +
            "d=informatica@2017")]
        public string PARQUEO03_30122021ConnectionString1 {
            get {
                return ((string)(this["PARQUEO03_30122021ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021;Persist Security Inf" +
            "o=True;User ID=sa;Password=informatica@2017")]
        public string PARQUEO03_30122021ConnectionString2 {
            get {
                return ((string)(this["PARQUEO03_30122021ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021_pruebas01;User ID=sa" +
            ";Password=informatica@2017")]
        public string PARQUEO03_30122021_pruebas01ConnectionString {
            get {
                return ((string)(this["PARQUEO03_30122021_pruebas01ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021_pruebas01;Persist Se" +
            "curity Info=True;User ID=sa;Password=informatica@2017")]
        public string PARQUEO03_30122021_pruebas01ConnectionString1 {
            get {
                return ((string)(this["PARQUEO03_30122021_pruebas01ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-1QD2KM3;Initial Catalog=PARQUEO03_30122021;Persist Security I" +
            "nfo=True;User ID=sa;Password=informatica@2017")]
        public string PARQUEO03_30122021ConnectionString3 {
            get {
                return ((string)(this["PARQUEO03_30122021ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021;User ID=SA;Password=" +
            "informatica@2017")]
        public string PARQUEO03_30122021ConnectionString4 {
            get {
                return ((string)(this["PARQUEO03_30122021ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021_prueba;Integrated Se" +
            "curity=True")]
        public string PARQUEO03_30122021_pruebaConnectionString {
            get {
                return ((string)(this["PARQUEO03_30122021_pruebaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021_prueba;User ID=sa;Pa" +
            "ssword=informatica@2017")]
        public string PARQUEO03_30122021_pruebaConnectionString1 {
            get {
                return ((string)(this["PARQUEO03_30122021_pruebaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.17.208.73;Initial Catalog=PARQUEO03_30122021_prueba;Persist Secur" +
            "ity Info=True;User ID=sa;Password=informatica@2017")]
        public string PARQUEO03_30122021_pruebaConnectionString2 {
            get {
                return ((string)(this["PARQUEO03_30122021_pruebaConnectionString2"]));
            }
        }
    }
}
